### PR TITLE
[wip]: Supprt .NET Standard 2.0

### PR DESCRIPTION
**Pull request by MarianPalkus**
Hi,
i try to add support for .NET Standard 2.0 in https://github.com/ckimes89/graphql-net, since the project depends on this project, it is necessary to support .NET Standard 2.0 as well.

This PR is a first approach to this.

### CODE REVIEW

**Comment by rspeele** [comment]
Hey, looks good in general. What's the deal with the changes from `static let` to `let` in TestPrecedence?

Robert

**Comment by MarianPalkus** [comment]
Hey,
thanks for the quick feedback.

The changes from `static let` to `let` are a quick workaround for a runtime error which occurs for example when executing `FParsec.Pipes.Test.TestPrecedence.TestPrecedenceNoSpaces`:
```
Unable to create instance of class FParsec.Pipes.Test.TestPrecedence. Error: System.InvalidOperationException: The static initialization of a file or type resulted in static data being accessed recursively before it was fully initialized..

Stack trace:
    at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.FailStaticInit()
   at FParsec.Pipes.Test.TestPrecedence..ctor() in /Users/map/Projects/FParsec-Pipes/FParsec-Pipes-Test/TestPrecedence.fs:line 54

```
My f# knowledge is not sufficient to identify the root of this problem. As to my understanding there is a static member of `TestPrecedence` or a referenced class which is not initialized when the tests is executed? Can you give me a hint how to solve it properly?

I also wanted to give a little summary of todos and have some questions:

**Questions:**
- Which visual studio versions should be supported? Currently, it's Visual Studio 2012. Can we simply use VS 2017 as minimum vs verison?
- Currently, the target framework version is .NET 4.6. Should we multi-targeting this project to support .NET 4.6 and .NET Standard 2.0?

**TODOs**:

- [X] Migrate `FParsec-Pipes.Docs`
- [X] Use the API Portability Analyzer tool to analyze assemblies

api_analysis_report

The API Portability Analyzer tool reports some incompatibilities, yet i was able to build the project and run all unit-tests on MacOS and Windows using VS 2017. I am not sure how to properly interpret those results.

Greetings,
Marian

**Comment by rspeele** [comment]
Sorry it's taken me a while to get back to this, and thank you for all your work!

I guess in answer to your question:

> Currently, the target framework version is .NET 4.6. Should we multi-targeting this project to support .NET 4.6 and .NET Standard 2.0?

I'm thinking **yes** but I'm not entirely sure.

To be honest I have not played with .NET Standard much but I notice that when I install a .NET Standard NuGet package (example: [Suave](http://www.nuget.org/packages/Suave)) in a .NET framework project, it goes and downloads about a zillion things (that are built into the framework) as dependencies. I would like existing .NET framework users of my Rezoom.SQL library not to have this experience so I assume that means targeting .NET framework 4.6 alongside the .NET standard 2.0.

Or would it require the .NET standard one to be an entirely separate package (so it gets a different dependency list)?

It's quite late here so I'm probably not making any sense.

**Comment by MarianPalkus** [comment]
Sounds meaningful.
I updated the `FParsec-Pipes.fsproj` to target `net46` as well. Building the project will output DLLs for both targets. 
(Had some issues building the project on Mac using Mono though..)

Both DLLs have yet to be included in the nuget package.

**Comment by rspeele** [comment]
Again, sorry I'm so slow. Can't believe it's been over a month -- time is flying by for me and I'm standing still.

Is this ready to test on my end? Will it install just the handful of dependencies (FParsec-Pipes, F# core) on 4.6 and the wheelbarrow of everything on .NET Core?

**Comment by modmoto** [comment]
@MarianPalkus 
Wow, this looks promising, can not wait for the grapqhl-net project to be able to be ported to .net core =)

**Comment by rspeele** [comment]
Closing this as we now target .NET Standard 2.0.

I'm sorry I never gave this a proper look. I waited until Visual Studio literally took away my option to target .NET Framework, and then "ported" it by making a new solution and copying all the source code over.  My sad lack of motivation should __not__ be taken as a negative comment on your work.

**Pull request closed without merging**
